Deployment triggered at Wed Mar  5 07:12:59 IST 2025

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -68,5 +68,14 @@ jobs:
 
             echo "Building React application..."
             npm run build
+            
+            
+            echo "Copying React build to Nginx directory..."
+            sudo rm -rf /var/www/html/*
+            sudo cp -r build/* /var/www/html/
+
+            echo "Restarting Nginx..."
+            sudo systemctl restart nginx
+            sudo systemctl status nginx --no-pager || { echo "Nginx failed!"; exit 1; }
 
             echo "Deployment successful!"
